added waiting for hostnet to come up to the autostart and daemon commands

diff --git a/conconj b/conconj
--- a/conconj
+++ b/conconj
@@ -354,9 +354,48 @@ if test "$CMD" = daemon || test "$CMD" = autostart || test "$CMD" = autostop; th
     fi
     (set x $A; shift; echo "info: daemon will start containers: $*" >&2)
     # !! TODO(pts): Add install command.
-    # !! TODO(pts): Wait for network first.
     CONAMES="$A"; CONT=1
     trap CONT= TERM INT QUIT
+    HOSTNETIP=
+    for CONAME in $CONAMES; do
+      read CONIP <"$CONAME".container/ipaddr 2>/dev/null ||:
+      case "$CONIP" in [1-9]*) HOSTNETIP=. ;; *) CONIP= ;; esac
+    done
+    if test "$HOSTNETIP" && ! read HOSTNETIP 2>/dev/null <conconj.hostnet; then
+      echo "fatal: missing or empty: $CODIR/conconj.hostnet"
+      exit 2
+    fi
+    if test "$HOSTNETIP"; then
+      S=
+      while test "$CONT"; do
+        ip -o addr | perl -we 'use integer; use strict;
+            die "fatal: bad netdevip: $ARGV[0]" if $ARGV[0] !~ m@\A(\d+)[.](\d+)[.](\d+)[.](\d+)(?:/32)?\Z(?!\n)@;
+            my $netdevip = unpack("N", pack("C4", $1, $2, $3, $4)); my $netdev;
+            while (<STDIN>) { chomp; my @l = split; if (@l > 3 and $l[2] eq "inet" and $l[1] ne "lo" and $l[3] =~ m@\A(\d+)[.](\d+)[.](\d+)[.](\d+)/(\d+)\Z(?!\n)@ and $5 != 32 and $5 >= 8 and $5 <= 32 and $l[1] ne "cc-localnet") {
+              my $ip = unpack("N", pack("C4", $1, $2, $3, $4)); my $mask = unpack("N", pack("N", -1 << (32 - $5))); if (($ip & $mask) == ($netdevip & $mask)) {
+                die "fatal: multiple network devices for hostnetip: $ARGV[0]\n" if defined($netdev);  # The $5 != 32 check above ensures that cc-hostnet is ignored here.
+                $netdev = $l[1] } } }
+            exit(2) if !defined($netdev)' "$HOSTNETIP" && break
+        case "$S" in
+         "") S=1; echo "info: waiting indefinitely for hostnet to come up, IP address: $HOSTNETIP" >&2 ;;
+         1) S=2 ;; 2) S=4 ;; 4) S=8 ;; 8) S=16 ;; 16) S=32 ;; 32) S=64 ;;
+        esac
+        if test "$CMD" = daemon; then
+          # %% is the perl -e sleep... process. We kill it explicitly in case
+          # %% systemd has sent only us (conconj shell script) the TERM signal.
+          trap 'CONT=; kill -TERM %% 2>/dev/null' TERM INT QUIT
+          if test "$CONT"; then
+            perl -e 'sleep $ARGV[1] if $ARGV[0]' "$CONT" "$S" &
+            test "$CONT" || kill -TERM %% 2>/dev/null
+            wait
+          fi
+        else
+          perl -e 'sleep $ARGV[0]' "$S"
+        fi
+      done
+      test "$CMD" = daemon && trap CONT= TERM INT QUIT
+    fi
+    test "$S" || echo "info: hostnet is already up, IP address: $HOSTNETIP" >&2
     for CONAME in $CONAMES; do
       test "$CONT" || break
       if machinectl show "$CONAME" 2>/dev/null >&2; then
